up:
	docker compose up -d

down:
	docker compose down

restart:
	docker compose restart

logs:
	docker compose logs -f

status:
	docker ps

health:
	docker inspect kafka --format='{{json .State.Health}}'