name: 'incremental_sales_etl_dbt'
version: '1.0.0'
config-version: 2

profile: 'incremental_sales_etl_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  incremental_sales_etl_dbt:

    staging:
      +materialized: incremental
      +schema: staging

    marts:
      +materialized: table
      +schema: marts